name: Push latest to steam
on: workflow_dispatch

jobs:
  download_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release Tag for server
        id: get_server_tag
        run: |
          TAG=$(gh release list --repo SlimeVR/SlimeVR-Server --limit 1 --json tagName --jq '.[0].tagName')
          echo "LATEST_SERVER_TAG=$TAG" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Base Directories
        run: |
          mkdir -p release/linux/x64/SlimeVR/jre 
          mkdir -p release/linux/x64/SlimeVR/lib
          mkdir -p release/linux/aarch64/SlimeVR/jre
          mkdir -p release/linux/aarch64/SlimeVR/lib
          mkdir -p release/windows/x64/SlimeVR/jre 
          mkdir -p release/windows/x64/SlimeVR/slimevr_usb_drivers

      - name: Move Assets to Depots
        run: |
          mv depots/linux/launch.sh release/linux/launch.sh
          mv depots/linux/x64/SlimeVR/jre/* release/linux/x64/SlimeVR/jre/
          mv depots/linux/x64/SlimeVR/lib/* release/linux/x64/SlimeVR/lib/
          mv depots/linux/aarch64/SlimeVR/jre/* release/linux/aarch64/SlimeVR/jre/
          mv depots/linux/aarch64/SlimeVR/lib/* release/linux/aarch64/SlimeVR/lib/
          mv depots/windows/x64/SlimeVR/slimevr_usb_drivers/* release/windows/x64/SlimeVR/slimevr_usb_drivers/
          mv depots/windows/x64/SlimeVR/jre/* release/windows/x64/SlimeVR/jre/

      # --- Start of Windows ---
      - name: "Get windows server"
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "SlimeVR/SlimeVR-Server"
          version: "latest"
          file: "SlimeVR-win64.zip"

      - name: "Unzip windows server"
        run: |
          unzip -o SlimeVR-win64.zip -d release/windows/x64/SlimeVR/

      - name: "Get Windows OpenVr Driver"
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "SlimeVR/SlimeVR-OpenVR-Driver"
          version: "latest"
          file: "slimevr-openvr-driver-win64.zip"

      - name: "Unzip Windows OpenVR Driver"
        run: |
          unzip slimevr-openvr-driver-win64.zip -d temp_win_driver
          mv temp_win_driver/slimevr/* release/windows/
          rm -rf temp_win_driver
      # --- End of Windows ---

      - name: "Get Linux release"
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "SlimeVR/SlimeVR-Server"
          version: "latest"
          file: "SlimeVR-amd64.deb"

      # --- Start of Linux x64
      - name: "Unzip linux release"
        run: |
          mkdir -p release/linux/x64
          ar x SlimeVR-amd64.deb
          tar -xvf data.tar.xz -C ./release/linux/x64/SlimeVR/ --strip-components=3 "./opt/SlimeVR"

      - name: "Get linux OpenVR Driver"
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "SlimeVR/SlimeVR-OpenVR-Driver"
          version: "latest"
          file: "slimevr-openvr-driver-x64-linux.zip"

      - name: "Unzip linux OpenVR Driver"
        run: |
          unzip slimevr-openvr-driver-x64-linux.zip -d temp_linux_driver
          mv temp_linux_driver/slimevr/* release/linux/
          rm -rf temp_linux_driver
      # --- End of Linx x64 ---

      # --- Start of Linux aarch64 ---
      - name: "Get Linux ARM64 release"
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "SlimeVR/SlimeVR-Server"
          version: "latest"
          file: "SlimeVR-aarch64.deb"

      - name: "Unzip linux ARM64 release"
        run: |
          mkdir -p release/linux/aarch64
          ar x SlimeVR-aarch64.deb
          tar -xvf data.tar.xz -C ./release/linux/aarch64/SlimeVR/ --strip-components=3 "./opt/SlimeVR"
          rm -f data.tar.xz control.tar.gz debian-binary SlimeVR-aarch64.deb

      - name: "Move linux ARM64 Driver"
        run: |
          mkdir -p release/linux/bin/linuxarm64/
          mv depots/linux/bin/linuxarm64/* release/linux/bin/linuxarm64/

      - name: "Get linux aarch64 OpenVR Driver"
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "SlimeVR/SlimeVR-OpenVR-Driver"
          version: "latest"
          file: "slimevr-openvr-driver-aarch64-linux.zip"

      - name: "Unzip linux aarch64 OpenVR Driver"
        run: |
          unzip -o slimevr-openvr-driver-aarch64-linux.zip -d temp_linux_arm_driver
          mv temp_linux_arm_driver/slimevr/* release/linux/
          rm -rf temp_linux_arm_driver
      # --- End of Linux aarch64

      - name: "Move installscripts to windows depot"
        run: |
          mv scripts/Installscript.vdf release/windows/Installscript.vdf
          mv scripts/installusbdrivers.bat release/windows/x64/SlimeVR/installusbdrivers.bat

      - name: "Deploy to steam"
        uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
          appId: 3245490
          buildDescription: "CI Build for release"
          rootPath: .
          depot1Path: release/windows
          depot1InstallScriptPath: release/windows
          depot2Path: release/linux
          #depot3path: release/macos
          releaseBranch: actions
