name: Push latest release to steam
on: workflow_dispatch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Base Directories  
        run: |
          mkdir -p release/windows64/jre 
          mkdir -p release/linux64/jre 
          mkdir -p release/windows64/slimevr_usb_drivers

      - name: Move Assets to Depots
        run: |
          mv depots/linux64/launch.sh release/linux64/launch.sh
          mv depots/linux64/jre/* release/linux64/jre/
          mv depots/windows64/slimevr_usb_drivers/* release/windows64/slimevr_usb_drivers/
          mv depots/windows64/jre/* release/windows64/jre/

      - name: 'Get windows server'
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'SlimeVR/SlimeVR-Server'
          version: 'latest'
          file: 'SlimeVR-win64.zip'

      - name: 'Unzip windows server' 
        run: |
          unzip -o SlimeVR-win64.zip -d release/windows64
      
      - name: 'Get Windows OpenVr Driver'
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'SlimeVR/SlimeVR-OpenVR-Driver'
          version: 'latest'
          file: 'slimevr-openvr-driver-win64.zip'

      - name: 'Unzip Windows OpenVR Driver'
        run: |
          unzip slimevr-openvr-driver-win64.zip -d temp_win_driver
          rm -rf release/windows64/slimevr-openvr-driver-win64
          mv temp_win_driver/slimevr release/windows64/slimevr-openvr-driver-win64
          rm -rf temp_win_driver

      - name: 'Get Linux release'
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'SlimeVR/SlimeVR-Server'
          version: 'latest'
          file: 'SlimeVR-amd64.deb'
        
      - name: 'Unzip linux release'
        run: |
          mkdir -p release/linux64
          ar x SlimeVR-amd64.deb
          tar -xvf data.tar.xz -C ./release/linux64 --strip-components=3 "./opt/SlimeVR"

      - name: 'Get linux OpenVR Driver'
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'SlimeVR/SlimeVR-OpenVR-Driver'
          version: 'latest'
          file: 'slimevr-openvr-driver-x64-linux.zip'
      
      - name: 'Unzip linux OpenVR Driver'
        run: |
          unzip slimevr-openvr-driver-x64-linux.zip -d temp_linux_driver
          rm -rf release/linux64/slimevr-openvr-driver-x64-linux
          mv temp_linux_driver/slimevr release/linux64/slimevr-openvr-driver-x64-linux
          rm -rf temp_linux_driver

      - name: 'Move installscripts to windows depot'
        run: |
          mv scripts/Installscript.vdf release/windows64/Installscript.vdf
          mv scripts/installusbdrivers.bat release/windows64/installusbdrivers.bat

      - name: 'Deploy to steam'
        uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}          
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}          
          appId: 3245490
          buildDescription: "Github workflow build"
          rootPath: .
          depot1Path: release/windows64
          depot1InstallScriptPath: release/windows64
          depot2Path: release/linux64
          releaseBranch: actions